### ISSUE TITLE
Peer to peer code review (M2-W4-D4)

### ISSUE THREAD

**Issue by zmekonnen251** [jerryowusu/LeaderBoard#4]
### Hey jerry you did an amazing job so far :+1: 

- [x] you used too many colors in this simple project. we think it is not good practice.
- [x] if you add /dist at the end of your live demo it will work. [live demo](https://jerryowusu.github.io/LeaderBoard/dist/ )

**Comment by jerryowusu** [comment]
Resolved. Thanks alot
